"""
Flask Web Server for Pluto AI Bot
Run after Main.py to start the web interface on localhost:5000
"""

import os
import sys

def check_and_install_dependencies() -> None:
    """Verify and install dependencies using pip"""
    required = {
        "flask": "Flask==3.0.0",
        "flask_cors": "Flask-CORS==4.0.0",
        "dotenv": "python-dotenv==1.0.0",
        "edge_tts": "edge-tts==6.1.10",
        "groq": "groq==0.9.0",
        "cohere": "cohere==5.0.1",
        "requests": "requests==2.31.0",
        "pyautogui": "pyautogui==0.9.53",
        "speech_recognition": "SpeechRecognition==3.10.0",
        "PyQt5": "pyQt5==5.15.9",
        "PIL": "pillow==10.1.0",
        "googlesearch": "googlesearch-python==1.2.3",
        "rich": "rich==13.7.0",
        "numpy": "numpy>=1.20.0",
        "sounddevice": "sounddevice>=0.4.0",
        "scipy": "scipy>=1.7.0",
        "pygame": "pygame>=2.0.0",
        "psutil": "psutil>=5.9.0"
    }
    
    missing = []
    for module, package in required.items():
        try:
            __import__(module)
        except ImportError:
            missing.append(package)
            
    if missing:
        print(f"[System] Verifying environment dependencies...")
        print(f"[System] Missing packages: {missing}")
        print("[System] Setting up environment, please wait...")
        import subprocess
        try:
            subprocess.check_call([sys.executable, "-m", "pip", "install", *missing])
            print("[System] ✓ Setup complete!")
        except Exception as e:
            print(f"[Error] Installation failed: {e}")
            print("[System] Attempting to install all from Requirements.txt...")
            try:
                subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", "Requirements.txt"])
                print("[System] ✓ Setup complete from Requirements.txt!")
            except Exception as ex:
                print(f"[Error] Failed to install requirements: {ex}")

check_and_install_dependencies()

import json
import threading
from datetime import datetime
from flask import Flask, render_template, request, jsonify, send_from_directory, Response
from flask_cors import CORS
from dotenv import dotenv_values

# Add project paths
sys.path.append(os.path.dirname(__file__))
sys.path.append(os.path.join(os.path.dirname(__file__), 'Backend'))

from Backend.botcore import BotCore

# Initialize Flask app
app = Flask(__name__, 
           template_folder=os.path.join(os.path.dirname(__file__), 'Frontend'),
           static_folder=os.path.join(os.path.dirname(__file__), 'Frontend', 'Graphics'))

CORS(app)

# Load environment variables
env_vars = dotenv_values(".env")
USERNAME = env_vars.get("Username", "User")
ASSISTANT_NAME = env_vars.get("Assistantname", "Assistant")

# Initialize BotCore instance
bot_instance = BotCore(gui_mode=True)
bot_instance.running = True

# Chat history storage
chat_history = []
chat_history_file = os.path.join(os.path.dirname(__file__), 'Data', 'web_chat_history.json')


def load_chat_history():
    """Load chat history from file"""
    try:
        if os.path.exists(chat_history_file):
            with open(chat_history_file, 'r', encoding='utf-8') as f:
                return json.load(f)
    except Exception as e:
        print(f"[Error] Loading chat history: {e}")
    return []


def save_chat_history():
    """Save chat history to file"""
    try:
        os.makedirs(os.path.dirname(chat_history_file), exist_ok=True)
        with open(chat_history_file, 'w', encoding='utf-8') as f:
            json.dump(chat_history, f, indent=2, ensure_ascii=False)
    except Exception as e:
        print(f"[Error] Saving chat history: {e}")

# Register voice mode message synchronization callback
def on_bot_voice_message(user_msg, bot_msg):
    from datetime import datetime
    chat_entry = {
        'timestamp': datetime.now().isoformat(),
        'user': user_msg,
        'bot': bot_msg
    }
    chat_history.append(chat_entry)
    if len(chat_history) > 1000:
        chat_history.pop(0)
    save_chat_history()

bot_instance.register_message_callback(on_bot_voice_message)


@app.route('/')
def index():
    """Serve the main web interface"""
    return render_template('index.html')


@app.route('/api/tts')
def tts_stream():
    """Stream TTS audio generated by edge-tts in real-time"""
    text = request.args.get('text', '').strip()
    if not text:
        return jsonify({'error': 'No text provided'}), 400
        
    try:
        import edge_tts
        import asyncio
        
        voice = env_vars.get("AssistantVoice", "en-IN-PrabhatNeural")
        
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
            
        async def get_audio_data():
            communicate = edge_tts.Communicate(text, voice, pitch='+5Hz', rate='+13%')
            audio_bytes = b""
            async for chunk in communicate.stream():
                if chunk["type"] == "audio":
                    audio_bytes += chunk["data"]
            return audio_bytes
            
        try:
            audio_data = loop.run_until_complete(get_audio_data())
        finally:
            loop.close()
            
        return Response(audio_data, mimetype="audio/mpeg")
    except Exception as e:
        print(f"[Error] TTS generation failed: {e}")
        return jsonify({'error': str(e)}), 500


@app.route('/images/<path:filename>')
def serve_image(filename):
    """Serve generated images from the Generated_Images folder"""
    return send_from_directory(os.path.join(os.path.dirname(__file__), 'Generated_Images'), filename)


@app.route('/gif')
def serve_gif():
    """Serve the Jarvis GIF animation"""
    if os.path.exists(os.path.join(os.path.dirname(__file__), 'Data', 'jarvis.gif')):
        return send_from_directory(os.path.join(os.path.dirname(__file__), 'Data'), 'jarvis.gif')
    elif os.path.exists(os.path.join(os.path.dirname(__file__), 'Frontend', 'Jarvis.gif')):
        return send_from_directory(os.path.join(os.path.dirname(__file__), 'Frontend'), 'Jarvis.gif')
    return 'GIF not found', 404



@app.route('/chat', methods=['POST'])
def chat():
    """Process chat message and return response"""
    try:
        data = request.json
        user_message = data.get('message', '').strip()
        
        if not user_message:
            return jsonify({'response': 'Please enter a message!'}), 400
        
        # Process message with bot
        bot_response = bot_instance.process_input(user_message)
        
        # Store in chat history
        chat_entry = {
            'timestamp': datetime.now().isoformat(),
            'user': user_message,
            'bot': bot_response
        }
        chat_history.append(chat_entry)
        
        # Save history (limit to last 1000 messages)
        if len(chat_history) > 1000:
            chat_history.pop(0)
        save_chat_history()
        
        return jsonify({
            'response': bot_response,
            'timestamp': chat_entry['timestamp']
        })
    
    except Exception as e:
        error_msg = f"Error processing request: {str(e)}"
        print(f"[Error] {error_msg}")
        return jsonify({'response': f'❌ {error_msg}'}), 500


@app.route('/api/history', methods=['GET'])
def get_history():
    """Get chat history"""
    try:
        limit = request.args.get('limit', 100, type=int)
        return jsonify({
            'history': chat_history[-limit:],
            'total': len(chat_history)
        })
    except Exception as e:
        return jsonify({'error': str(e)}), 500


@app.route('/api/status', methods=['GET'])
def get_status():
    """Get bot status and system metrics"""
    cpu_percent = 0.0
    memory_percent = 0.0
    try:
        import psutil
        cpu_percent = psutil.cpu_percent()
        memory_percent = psutil.virtual_memory().percent
    except Exception:
        import random
        cpu_percent = round(random.uniform(5.0, 15.0), 1)
        memory_percent = round(random.uniform(30.0, 50.0), 1)

    # API keys configuration check
    groq_ok = bool(env_vars.get("GroqAPIKey") and not env_vars.get("GroqAPIKey").startswith("your_"))
    cohere_ok = bool(env_vars.get("CohereAPIKey") and not env_vars.get("CohereAPIKey").startswith("your_"))
    huggingface_ok = bool(env_vars.get("HUGGINGFACE_API_KEY") and not env_vars.get("HUGGINGFACE_API_KEY").startswith("your_"))

    return jsonify({
        'status': 'online' if bot_instance.running else 'offline',
        'assistant_name': ASSISTANT_NAME,
        'username': USERNAME,
        'uptime': 'running',
        'messages_processed': len(chat_history),
        'metrics': {
            'cpu': cpu_percent,
            'memory': memory_percent
        },
        'apis': {
            'groq': groq_ok,
            'cohere': cohere_ok,
            'huggingface': huggingface_ok
        }
    })


@app.route('/api/clear-history', methods=['POST'])
def clear_history():
    """Clear chat history"""
    try:
        global chat_history
        chat_history = []
        save_chat_history()
        return jsonify({'success': True, 'message': 'Chat history cleared'})
    except Exception as e:
        return jsonify({'success': False, 'error': str(e)}), 500


@app.errorhandler(404)
def not_found(error):
    """Handle 404 errors"""
    return jsonify({'error': 'Endpoint not found'}), 404


@app.errorhandler(500)
def internal_error(error):
    """Handle 500 errors"""
    return jsonify({'error': 'Internal server error'}), 500


def main():
    """Main function to start the Flask server"""
    print(f"\n{'='*60}")
    print(f"🚀 {ASSISTANT_NAME} AI - Web Server Starting...")
    print(f"{'='*60}")
    print(f"📝 Bot Instance: {ASSISTANT_NAME}")
    print(f"👤 User: {USERNAME}")
    print(f"🌐 Server: http://localhost:5000")
    print(f"🔗 API Base: http://localhost:5000/api")
    print(f"{'='*60}\n")
    
    # Load previous chat history
    global chat_history
    chat_history = load_chat_history()
    print(f"[Info] Loaded {len(chat_history)} previous messages")
    
    # Start Flask server
    app.run(host='0.0.0.0', port=5000, debug=False, threaded=True)


if __name__ == '__main__':
    main()
